config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tweets do
    resources :likes
  end
  get 'search', to: 'tweets#search'
  post 'friends/:friend_id', to: 'friends#create'
  root to: "tweets#index"
      # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :hashtags
  scope :tweets_for_me, ->(friend_ids) { joins(user: :friends).where(tweets: { user_id: friend_ids }) }

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    # binding.pry
    @tweet = Tweet.new
    if current_user
      friend_ids = Friend.where(user_id: current_user).pluck(:friends_id)      
      @tweets = Tweet.where(user_id: friend_ids)
    else
      @tweets = Tweet.includes([:user]).all
    end

    @tweets = @tweets.order(updated_at: :desc).page(params[:page]).per(10)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.new tweet_params

    if current_user
      @tweet.user_id = current_user.id
    end

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @tweet = Tweet.new
    if current_user
      friend_ids = Friend.where(user_id: current_user).pluck(:friends_id)      
      @tweets = Tweet.where(user_id: friend_ids)
    else
      @tweets = Tweet.includes([:user]).all
    end

    @tweets = @tweets.where('lower(content) LIKE :content', content: "%#{params[:content].downcase}%").page(params[:page])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      begin
      @tweet = Tweet.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to tweets_url, notice: "ERROR: Tweet no encontrado"
      end
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :active)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def render_with_tags(content)
    content.gsub(/#\w+/){|word| link_to word, "/search?content=#{word.delete('#')}"}.html_safe
  end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Tweets</h1>
<%if user_signed_in?%>
  <%= render 'form', tweet: @tweet %>
<%end%>
<br>

<%= form_with url: 'search', method: :get do |form| %>
  <div>
    <%=form.label :content, "Buscar tweets:" %>
    <%= form.text_field :content, class:'form-control' %>
  </div>
  <%= form.submit "Buscar" %>
<% end %>
<br>
<%=paginate @tweets %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th>Photo</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @tweets.each do |tweet| %>
      <tr>
        <td>
          <%= render_with_tags(tweet.content) %> 
          <p><%= tweet.likes.count %> 
          <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        </td>        
        <td class= "border border-info" ><%= image_tag (tweet.user.photo || '') %></td>
        <td><%= tweet.active %></td>
        <% if tweet.created_at < 1.hour.ago%> 
        <td><%= link_to time_ago_in_words(tweet.created_at), tweet %></td>
        <% else %>
        <td> <%= link_to time_ago_in_words(tweet.created_at), tweet %> </td>
        <% end %>
        <td>
        <% if current_user %>
        <%= link_to 'Edit', edit_tweet_path(tweet) %>
        <% end %>
        </td>
        <td>
        <% if current_user %>
        <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/search.html.erb
<h1> Search Results </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th>Photo</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %> <p><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p></td>        
        <td class= "border border-info" ><%= image_tag (tweet.user.photo || '') %></td>
        <td><%= tweet.active %></td>
        <% if tweet.created_at < 1.hour.ago%> 
        <td><%= link_to time_ago_in_words(tweet.created_at), tweet %></td>
        <% else %>
        <td> <%= link_to time_ago_in_words(tweet.created_at), tweet %> </td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @tweet.photo %>
</p>

<p>
  <strong>Retweets:</strong>
  <%= @tweet.retweets %>
</p>

<p>
  <strong>Active:</strong>
  <%= @tweet.active %>
</p>

<p>
  <%= @tweet.likes.count %>
  <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes' %> 
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

<% if current_user %>    
<%= button_to 'Like', tweet_likes_path(@tweet), method: :post, disabled: !current_user %>
<% end %>